"use client";
import {useState} from "react";
const API="http://127.0.0.1:8765/api";
type Warning={code:string;message:string;page?:number};
type Document={document_id:string;original_filename:string;sha256:string;byte_size:number;page_count:number;status:string;profile:string|null};
type Run={run_id:string;status:string;operation:string;mode:string;model_calls:number;stages:Record<string,string>;outputs:Record<string,string>;warnings:Warning[];errors:Warning[];parser_configuration:Record<string,unknown>};
type Tree={document_id:string;source_sha256:string;run_id:string;tier:string;provenance_mode:string;warnings:Warning[];validation:{structure_valid:boolean;status:string;objective_count:number;official_text_confirmed:false};topics:{topic_code:string;topic_name:string;subtopics:{subtopic_code:string;subtopic_name:string;notes:string[];objectives:{objective_code:string;official_text:string;source_id:string;canonical:{status:string;reason:string}}[]}[]}[]};
type Capability={CURRICULUM_BROWSABLE:boolean;LESSON_GENERATION_SUPPORTED:false;QUESTION_GENERATION_SUPPORTED:false;PRESENTATION_SUPPORTED:false;reason:string;target:Record<string,unknown>};
async function get<T>(path:string,options?:RequestInit):Promise<T>{const r=await fetch(API+path,options);const data=await r.json();if(!r.ok)throw new Error(data.error?`${data.error.code}: ${data.error.message}`:JSON.stringify(data.detail));return data;}
function Details({value,label}:{value:unknown;label:string}){return <details><summary>{label}</summary><pre>{JSON.stringify(value,null,2)}</pre></details>;}
export function SyllabusIngestion(){
  const [file,setFile]=useState<File|null>(null),[doc,setDoc]=useState<Document|null>(null),[tier,setTier]=useState("foundation");
  const [start,setStart]=useState(21),[end,setEnd]=useState(22),[ex,setEx]=useState<string|null>(null),[run,setRun]=useState<Run|null>(null);
  const [tree,setTree]=useState<Tree|null>(null),[cap,setCap]=useState<Capability|null>(null),[selected,setSelected]=useState("2.1");
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[consent,setConsent]=useState(false),[validation,setValidation]=useState<unknown>(null);
  async function post<T>(path:string,body:BodyInit,type="application/json"){const {token}=await get<{token:string}>("/session");return get<T>(path,{method:"POST",headers:{"Content-Type":type,"X-Console-Token":token},body});}
  async function upload(){if(!file)return;setBusy(true);setError("");setDoc(null);setRun(null);setEx(null);setTree(null);setCap(null);setValidation(null);try{setDoc(await post<Document>(`/syllabi?filename=${encodeURIComponent(file.name)}`,file,"application/pdf"));}catch(e){setError(String(e));}finally{setBusy(false);}}
  async function poll(initial:Run){let r=initial;setRun(r);while(r.status==="queued"||r.status==="running"){await new Promise(resolve=>setTimeout(resolve,250));r=await get<Run>(`/curriculum-runs/${r.run_id}`);setRun(r);}if(r.errors.length)setError(r.errors.map(e=>`${e.code}: ${e.message}`).join("; "));return r;}
  async function extract(){if(!doc)return;setBusy(true);setError("");setEx(null);setTree(null);setCap(null);setValidation(null);try{const r=await poll(await post<Run>(`/syllabi/${doc.document_id}/extract`,JSON.stringify({tier,start_page:start,end_page:end})));if(r.status==="succeeded")setEx(r.run_id);}catch(e){setError(String(e));}finally{setBusy(false);}}
  async function parse(mode:"preserved"|"live"){if(!doc||!ex)return;setBusy(true);setError("");setTree(null);setCap(null);setValidation(null);try{const r=await poll(await post<Run>(`/syllabi/${doc.document_id}/parse`,JSON.stringify({extraction_run_id:ex,mode,confirm_model_call:mode==="live"&&consent})));if(r.outputs.validation)setValidation(await get(`/curriculum-runs/${r.run_id}/validation`));if(r.status==="succeeded"){setTree(await get<Tree>(`/curriculum-runs/${r.run_id}/tree`));setSelected("2.1");setCap(await get<Capability>(`/curriculum-runs/${r.run_id}/capabilities?subtopic=2.1`));}}catch(e){setError(String(e));}finally{setBusy(false);setConsent(false);}}
  async function select(code:string){if(!tree)return;setSelected(code);setCap(null);try{setCap(await get<Capability>(`/curriculum-runs/${tree.run_id}/capabilities?subtopic=${encodeURIComponent(code)}`));}catch(e){setError(String(e));}}
  const sub=tree?.topics[0].subtopics.find(s=>s.subtopic_code===selected);
  return <section className="console-panel" data-testid="syllabus-ingestion" style={{marginBottom:18}}><h2>Upload & inspect syllabus PDF</h2><p>Supported: known 2017 Edexcel 4MA1 Topic 2 edition, text PDF only. No OCR, Word or generic syllabus support.</p><p>Upload and extraction never call a model. Uploaded curriculum remains UNTRUSTED / REVIEWABLE.</p>
    <label htmlFor="syllabus-file">PDF file · maximum 10 MiB</label><input id="syllabus-file" type="file" accept="application/pdf,.pdf" disabled={busy} onChange={e=>setFile(e.target.files?.[0]??null)}/><button onClick={upload} disabled={!file||busy}>Upload PDF · no model</button>
    {error&&<p role="alert" className="warning">{error}</p>}
    {doc&&<><p data-testid="document-status">{doc.original_filename} · {doc.page_count} pages · {doc.status}</p><Details value={doc} label="Immutable document identity"/>
      <div className="action-row"><div><label htmlFor="ingest-tier">Uploaded curriculum tier</label><select id="ingest-tier" value={tier} disabled={busy} onChange={e=>{setTier(e.target.value);setStart(e.target.value==="foundation"?21:37);setEnd(e.target.value==="foundation"?22:38);setEx(null);setTree(null);setCap(null);setRun(null);setValidation(null);}}><option value="foundation">Foundation</option><option value="higher">Higher</option></select></div><label>PDF start page <input aria-label="PDF start page" type="number" value={start} disabled={busy} onChange={e=>{setStart(Number(e.target.value));setEx(null);}}/></label><label>PDF end page <input aria-label="PDF end page" type="number" value={end} disabled={busy} onChange={e=>{setEnd(Number(e.target.value));setEx(null);}}/></label><button onClick={extract} disabled={busy}>Extract text · no model</button></div>
      <button onClick={()=>parse("preserved")} disabled={!ex||busy}>Replay preserved parse · 0 model calls</button><p className="tiny">Replay is available only for the exact known PDF and extraction. It reuses historical parser output, not a fresh AI response.</p>
      <label><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/> I authorize one paid AI parse of these extracted pages.</label><button onClick={()=>parse("live")} disabled={!ex||!consent||busy}>Parse with AI · explicit model call</button>
    </>}
    {run&&<><p role="status" data-testid="ingestion-status">{run.operation} · {run.status} · {run.mode} · model calls: {run.model_calls}</p><Details value={run} label="Real ingestion run / stage evidence"/>{run.warnings.map((w,i)=><p className="warning" key={i}>{w.code}: {w.message}</p>)}</>}
    {validation!==null&&<Details value={validation} label="Structural validation result"/>}
    {tree&&<section data-testid="uploaded-tree"><h3>Uploaded {tree.tier} · Topic {tree.topics[0].topic_code}: {tree.topics[0].topic_name}</h3><p>STRUCTURE_VALID · {tree.validation.objective_count} objectives · official text confirmed: false</p><p>Provenance mode: {tree.provenance_mode}. No academic approval.</p><label htmlFor="uploaded-subtopic">Select uploaded subtopic</label><select id="uploaded-subtopic" value={selected} onChange={e=>select(e.target.value)}>{tree.topics[0].subtopics.map(s=><option key={s.subtopic_code} value={s.subtopic_code}>{s.subtopic_code} {s.subtopic_name}</option>)}</select>{sub?.notes.map((n,i)=><p key={i}>{n}</p>)}{sub?.objectives.map(o=><article className="objective" key={o.source_id}><strong>{o.objective_code}</strong><p>{o.official_text}</p><code>{o.source_id}</code><p>{o.canonical.status}: {o.canonical.reason}</p></article>)}
      {cap&&<div data-testid="uploaded-capabilities"><p>CURRICULUM_BROWSABLE: {String(cap.CURRICULUM_BROWSABLE)}</p><p>LESSON_GENERATION_SUPPORTED: false</p><p>QUESTION_GENERATION_SUPPORTED: false</p><p>PRESENTATION_SUPPORTED: false</p><button disabled>Generate uploaded-topic lesson</button><p>{cap.reason}</p><Details value={cap.target} label="Selected target identity / future adapter boundary"/></div>}
    </section>}
  </section>;
}
