import {test,expect} from "@playwright/test";
import {resolve} from "node:path";
import {readFileSync} from "node:fs";
import {createHash} from "node:crypto";
const root=resolve(__dirname,"../../..");
const hash=(p:string)=>createHash("sha256").update(readFileSync(resolve(root,p))).digest("hex");
test("real PDF upload, extraction, preserved parse, selection and bounded capabilities",async({page})=>{
  const db=hash("var/p0_q2.sqlite3");const modelRequests:string[]=[];
  page.on("request",r=>{if(!r.url().startsWith("http://127.0.0.1:"))modelRequests.push(r.url());});
  await page.goto("/");const panel=page.getByTestId("syllabus-ingestion");
  await panel.locator('input[type="file"]').setInputFiles(resolve(root,"international-gcse-in-mathematics-spec-a.pdf"));
  await panel.getByRole("button",{name:"Upload PDF · no model",exact:true}).click();
  await expect(panel.getByTestId("document-status")).toContainText("UPLOADED");
  await expect(panel.getByTestId("ingestion-status")).toHaveCount(0);
  await expect(panel.getByRole("button",{name:"Parse with AI · explicit model call",exact:true})).toBeDisabled();
  await panel.getByRole("button",{name:"Extract text · no model",exact:true}).click();
  await expect(panel.getByTestId("ingestion-status")).toContainText("extract · succeeded");
  await expect(panel.getByTestId("ingestion-status")).toContainText("model calls: 0");
  await panel.getByRole("button",{name:"Replay preserved parse · 0 model calls",exact:true}).click();
  await expect(panel.getByTestId("uploaded-tree")).toBeVisible();
  await expect(panel.getByTestId("uploaded-tree")).toContainText("25 objectives");
  await expect(panel.getByTestId("uploaded-tree")).toContainText("EDX-4MA1-F-2.1-A");
  await expect(panel.getByTestId("uploaded-capabilities")).toContainText("CURRICULUM_BROWSABLE: true");
  await expect(panel.getByRole("button",{name:"Generate uploaded-topic lesson",exact:true})).toBeDisabled();
  await panel.locator("#uploaded-subtopic").selectOption("2.7");await expect(panel.getByTestId("uploaded-tree")).toContainText("EDX-4MA1-F-2.7-A");
  await panel.locator("#ingest-tier").selectOption("higher");
  await panel.getByRole("button",{name:"Extract text · no model",exact:true}).click();
  await expect(panel.getByTestId("ingestion-status")).toContainText("extract · succeeded");
  await panel.getByRole("button",{name:"Replay preserved parse · 0 model calls",exact:true}).click();
  await expect(panel.getByTestId("uploaded-tree")).toContainText("16 objectives");
  await expect(panel.getByTestId("uploaded-tree")).toContainText("EDX-4MA1-H-2.1-A");
  await expect(panel).toContainText("SYMBOL_EXTRACTION_WARNING");
  expect(modelRequests).toEqual([]);expect(hash("var/p0_q2.sqlite3")).toBe(db);
  await panel.screenshot({path:resolve(root,process.env.P6UI_ACCEPTANCE_DIR??"tmp/p6ui3-browser","ingestion-browser.png")});
});
